//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucoServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Round()
        {
            this.DealtCard = new HashSet<DealtCard>();
        }
    
        public int roundID { get; set; }
        public int matchID { get; set; }
        public int number { get; set; }
        public string status { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> winnerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealtCard> DealtCard { get; set; }
        public virtual Match Match { get; set; }
        public virtual User User { get; set; }
    }
}
