//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucoServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentBrackets
    {
        public int Id { get; set; }
        public int TournamentId { get; set; }
        public int Round { get; set; }
        public int Position { get; set; }
        public Nullable<int> Player1Id { get; set; }
        public Nullable<int> Player2Id { get; set; }
        public Nullable<int> WinnerId { get; set; }
        public string MatchId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Tournaments Tournaments { get; set; }
        public virtual User User2 { get; set; }
    }
}
