//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucoServer.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrucoServer.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello {0}!\n\n{1} has invited you to play a match.\nJoin using the code: {2}\n\nSee you at the table!.
        /// </summary>
        public static string EmailInvitationBody {
            get {
                return ResourceManager.GetString("EmailInvitationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation code - Truco Argentino.
        /// </summary>
        public static string EmailInvitationSubject {
            get {
                return ResourceManager.GetString("EmailInvitationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello {0},\n\nA recent login was detected on your Truco Argentino account.\nLogin time: {1} (Server time).\n\nIf it was you, you can ignore this message.\nIf not, please change your password immediately..
        /// </summary>
        public static string EmailLoginNotificactionBody {
            get {
                return ResourceManager.GetString("EmailLoginNotificactionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New login in Truco Argentino.
        /// </summary>
        public static string EmailLoginNotificationSubject {
            get {
                return ResourceManager.GetString("EmailLoginNotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello {0},\n\nThis is a confirmation message letting you know that your Truco Argentino password has been successfully changed.\nThis change was made: {1} (Server time).\n\nThank you for helping us keep your account secure. The Lotso Studios team..
        /// </summary>
        public static string EmailPasswordNotificationBody {
            get {
                return ResourceManager.GetString("EmailPasswordNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password successfully changed for your Truco Argentino account.
        /// </summary>
        public static string EmailPasswordNotificationSubject {
            get {
                return ResourceManager.GetString("EmailPasswordNotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your verification code is: {0}\n\nDo not share this code with anyone else.
        /// </summary>
        public static string EmailVerificationBody {
            get {
                return ResourceManager.GetString("EmailVerificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code - Truco Argentino.
        /// </summary>
        public static string EmailVerificationSubject {
            get {
                return ResourceManager.GetString("EmailVerificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This user already has an active session..
        /// </summary>
        public static string ExceptionTextLogin {
            get {
                return ResourceManager.GetString("ExceptionTextLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Too many login attempts have been detected. If you&apos;ve forgotten your password, use the &apos;Forgot your password?&apos; link below. Otherwise, please wait a moment and try again..
        /// </summary>
        public static string ExceptionTextTooManyAttempts {
            get {
                return ResourceManager.GetString("ExceptionTextTooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account is temporarily suspended due to toxic behavior..
        /// </summary>
        public static string ExceptionTextUserBanned {
            get {
                return ResourceManager.GetString("ExceptionTextUserBanned", resourceCulture);
            }
        }
    }
}
